version: '3.9'
services:
  frontend:
    build: ./frontend
    container_name: app-frontend
    ports:
      - 3000:3000
    platform: linux/x86_64
    working_dir: /app-frontend
    volumes: 
      - ./frontend:/app-frontend
      - /app-frontend/node_modules
    depends_on:
      - backend
  backend:
    container_name: app-backend
    build: ./backend
    ports:
      - 3001:3001
    platform: linux/x86_64
    working_dir: /app-backend
    volumes: 
      - ./backend:/app-backend
      - /app-backend/node_modules/bcrypt/
    depends_on:
      - db
    environment:
      - APP_PORT=3001
      - JWT_SECRET=jwt_secret
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123456
      - POSTGRES_HOST=db
      - POSTGRES_DB=personal_bank
      - POSTGRES_PORT=5432
  db:
    image: postgres
    container_name: db
    platform: linux/x86_64
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_USER=root
      - POSTGRES_DB=personal_bank
    restart: 'always'
    volumes:
      - pgdata:/data/postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      timeout: 10s
      retries: 5
    cap_add:
      - SYS_NICE

volumes:
  pgdata:
    driver: local