version: '3.9'
services:
  frontend:
    build: ./frontend
    container_name: app-frontend
    ports:
      - 3000:3000
    working_dir: /app-frontend
    depends_on:
      backend:
        condition: service_healthy
  backend:
    container_name: app-backend
    build: ./backend
    ports:
      - 3001:3001
    working_dir: /app-backend
    volumes: 
      - ./backend:/app-backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      - APP_PORT=3001
      - JWT_SECRET=jwt_secret
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123456
      - POSTGRES_HOST=db
      - POSTGRES_DB=personal_bank
      - POSTGRES_PORT=5432
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3001"]
      timeout: 10s
      retries: 5
  db:
    image: postgres
    container_name: db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_USER=root
      - POSTGRES_DB=personal_bank
    restart: 'always'
    volumes:
      - pgdata:/data/postgres
      - /app-backend/node_modules/bcrypt
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      timeout: 10s
      retries: 5
    cap_add:
      - SYS_NICE

volumes:
  pgdata:
    driver: local